changelog:
  categories:
    - title: Breaking Changes
      labels:
        - breaking
    - title: Features
      labels:
        - feature
        - enhancement
        - feat
    - title: Fixes
      labels:
        - bug
        - fix
    - title: Documentation
      labels:
        - documentation
        - docs
    - title: CI / Infra
      labels:
        - ci
        - infra
    - title: Other
      labels:
        - "*"
